In [2]:
!pip install tensorflow

INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
   ---------------------------------------- 0.0/276.5 MB ? eta -:--:--
   ---------------------------------------- 1.0/276.5 MB 21.4 MB/s eta 0:00:13
   ---------------------------------------- 1.9/276.5 MB 17.6 MB/s eta 0:00:16
   ---------------------------------------- 3.1/276.5 MB 17.7 MB/s eta 0:00:16
    --------------------------------------- 4.1/276.5 MB 17.6 MB/s eta 0:00:16
    --------------------------------------- 5.2/276.5 MB 17.6 MB/s eta 0:00:16
    --------------------------------------- 6.1/276.5 MB 17.8 MB/s eta 0:00:16
   - -------------------------------------- 7.2/276.5 MB 18.4 MB/s eta 0:00:15
   - -------------------------------------- 8.3/276.5 MB 18.9 MB/s eta 0:00:15
   - -------------------------------------- 9.4/276.5 MB 19.3 MB/s eta 0:00:14
   - -------------------------------------- 10.4/276.5 MB 19.2 MB/s eta

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mxnet 1.7.0.post2 requires numpy<1.17.0,>=1.8.2, but you have numpy 1.24.3 which is incompatible.
mxnet 1.7.0.post2 requires requests<2.19.0,>=2.18.4, but you have requests 2.28.1 which is incompatible.
azure-core 1.30.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
chromadb 0.4.21 requires tokenizers>=0.13.2, but you have tokenizers 0.10.3 which is incompatible.
eodhd 1.0.21 requires numpy==1.21.6, but you have numpy 1.24.3 which is incompatible.
fastapi 0.108.0 requires typing-extensions>=4.8.0, but you have typing-extensions 4.5.0 which is incompatible.
pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, bu

In [1]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense

e:\anaconda3\envs\llm\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (5.2.0)/charset_normalizer (None) doesn't match a supported version!
  warnings.warn(


In [2]:
# 레스토랑 리뷰 10개 정의
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
# label 정의
labels = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[4, 35, 48], [25, 27], [43, 30], [38, 34], [25, 34], [23], [23, 8], [5], [42, 26], [3, 7, 40, 29]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[ 4 35 48  0]
 [25 27  0  0]
 [43 30  0  0]
 [38 34  0  0]
 [25 34  0  0]
 [23  0  0  0]
 [23  8  0  0]
 [ 5  0  0  0]
 [42 26  0  0]
 [ 3  7 40 29]]


In [5]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433 (1.69 KB)
Trainable params: 433 (1.69 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [6]:
model.fit(padded_reviews,labels,epochs=100,verbose=0)

In [7]:
print(embedding_layer.get_weights()[0].shape)

(50, 8)
